# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-14 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_semi_restful', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Network',
            new_name='network',
        ),
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
